[package]
name = "fm-receiver"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
clap = { version = "3.0.13", features = ["derive"] }
futuresdr = { path = "../..", features=["soapy", "audio"] }
futuredsp = { path = "../../futuredsp", version = "0.0.4" }
futuresdr_macros = { path = "../../futuresdr-macros" }